production:
  adapter: postgresql
  url: postgres://localhost/gas_cable_development

development:
  adapter: postgresql
  url: postgres://localhost/gas_cable_development

test:
  adapter: postgresql
  url: postgres://localhost/gas_cable_test