production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  url: postgres://localhost/gas_cable_development

test:
  adapter: postgresql
  url: postgres://localhost/gas_cable_test